version: '3.8'

services:
  # Frontend React
  frontend:
    container_name: form-funiber
    build:
      context: ./frontend  # Ruta al directorio del frontend React
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Ajusta el puerto según sea necesario
    depends_on:
      - backend

  # Backend Laravel con PHP y Nginx
  backend:
    container_name: api
    build:
      context: ./backend 
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - database
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=127.0.0.1
      - DB_PORT=5432
      - DB_DATABASE=api_funiber
      - DB_USERNAME=postgres
      - DB_PASSWORD=12345

  # Base de Datos PostgreSQL
  database:
    container_name: postgres-database
    image: postgres:latest
    environment:
      - POSTGRES_DB=api_funiber
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - "5432:5432" 
